name: PyInstaller Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: macos
            cmd: pyinstaller -F -n updater
            file: updater
          - os: windows-latest
            target: windows
            cmd: pyinstaller -F -n updater
            file: updater.exe
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Build with pyinstaller for ${{matrix.target}}
        run: ${{matrix.cmd}}
      - name: Upload release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "latest"
          file: ./dist/${{matrix.file}}
          asset_name: ${{matrix.target}}-${{matrix.file}}
        
